#Geometry commands
/geom/setGeometry /home/sch52/code/paleo-bg-sim/macroFiles/geometry/ambe.mac

#Source commands
/generator/setSourceType meiHimeMuonGenerator
/generator/meiHimeMuonGenerator/setMuonEffectiveDepth 0.5 km
/generator/setNPS 200000

#Output commands
/output/setNeutronTallyTreeVolume Collimator
/output/setRecoilTreeVolume Target
/output/setVRMLOutputStatus 1

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
