#Geometry commands
/geom/setGeometry /macroFiles/geometry/ambe.mac

#Source commands
/generator/setSourceType CRYGenerator 
/generator/cry/setCRYFilename /home/sch52/code/paleo-bg-sim/data/cry_vt.root
/generator/setNPS 20

#Output commands
/output/setPrimariesTreeStatus 1
/output/setNeutronTallyTreeVolume Collimator
/output/setRecoilTreeVolume Target
/output/setVRMLOutputStatus 1

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
