#Geometry commands
/geom/setGeometry /macroFiles/geometry/conus_shield_with_lif.geo

#Source commands
/generator/setSourceType CRYGenerator 
/generator/cry/setCRYFilename /home/sch52/code/paleo-bg-sim/data/kll_muneu.root
#number of muons of 5m x 5m area in 10 min
#/generator/setNPS 32189906
/generator/setNPS 497

#Output commands
/output/setNeutronTallyTreeVolumes innerAir
/output/setRecoilTreeVolumes detector1 detector2 detector3 detector4
/output/setVRMLOutputStatus True

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
