#Geometry commands
/geom/setGeometry /macroFiles/geometry/leibstadt.geo

#Source commands
/generator/setSourceType diskSource 
/generator/diskSource/pdgCode 2112
/generator/diskSource/setDiskSourceType hist
/generator/diskSource/setDiskSourceSpectrumFilename /home/sch52/code/paleo-bg-sim/data/leibstadt_neutrons.root
/generator/diskSource/setDiskSourceSpectrumHistName hist
/generator/diskSource/setDiskSourceRadius 50 cm
/generator/diskSource/setDiskSourcePositionCmd 0 0 -141.2
/generator/diskSource/setDiskSourceAxis 0 0 1
/generator/diskSource/setDiskSourceDirection 0 1 1
#Norm from hist is 266.70 n/cm2/GWHr
#We're operating at 3.6GWhr = 960.12 n/cm2/GWHr
#Our disk is 50cm radius, so 7.54e7 n/hr
#If we want to run for a year that's 6.60571*10^10
#Split into 100 runs of 660 571 000
/generator/setNPS 66057100

#Output commands
/output/setNeutronTallyTreeVolumes WaterShielding30cm WaterShielding25cm WaterShielding20cm WaterShielding15cm WaterShielding10cm WaterShielding5cm LiF
/output/setRecoilTreeVolumes LiF
/output/setVRMLOutputStatus True

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
