#Geometry commands
/geom/setGeometry /macroFiles/geometry/meiHime.geo

#Source commands
/generator/setSourceType meiHimeMuonGenerator
/generator/meiHimeMuonGenerator/setMuonEffectiveDepth 5.993 km
/generator/setNPS 200

#Output commands
/output/setMINTreeStatus 1
/output/setNeutronTallyTreeVolume AirCavity
/output/setVRMLOutputStatus 1

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
