#Geometry commands
/geom/setGeometry /macroFiles/geometry/meiHime.geo

#Source commands
/generator/setSourceType muteGenerator
/generator/muteGenerator/setMuteHistFilename /home/pspranav/paleo-bg-mute/muteGenerator/GranSasso.root
/generator/muteGenerator/setMuteOverburdenType mountain
/generator/muteGenerator/setMuteMountainProfileFilename /home/pspranav/paleo-bg-mute/muteGenerator/data/mountains/lngs_mountain.txt
/generator/muteGenerator/setMuteFluxNormalization 2.4714067093616173e-08
/generator/setNPS 10000000

#Output commands
/output/setNeutronTallyTreeVolumes AirCavity
/output/setVRMLOutputStatus 0

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
