#Geometry commands
/geom/setGeometry /macroFiles/geometry/sct_thrower.geo

#Source commands
/generator/setSourceType SCTGenerator
/generator/SCTGenerator/setSCTFilename /home/pspranav/paleo-bg-sim-build/outputFiles/tosvtad/SCT/8000m_StandardRock_26x26.root
/generator/SCTGenerator/setSCTBootstrap standard
/generator/setNPS 100000000

#Output commands
/output/setPrimariesTreeStatus false
/output/setRecoilTreeVolumes Crystal
/output/setVRMLOutputStatus false

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0



