#Geometry commands
/geom/setGeometry /macroFiles/geometry/testGeometry.mac

#Source commands
/generator/setSourceType meiHimeMuonGenerator
/generator/meiHimeMuonGenerator/setMuonEffectiveDepth 6.0 km
/generator/setNPS 100

#Output commands
/output/setNeutronTallyTreeVolume AirCavity
/output/setRecoilTreeVolume Target
/output/setVRMLOutputStatus 1

#Verbosity settings
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
