#Geometry commands
/geom/setOverburdenSideLength 20.0 m
/geom/setAirCavitySideLength 6.0 m
/geom/setTargetSideLength 1.0 cm
/geom/setOverburdenMaterial norite
/geom/setTargetMaterial norite

#Source commands
/generator/setSourceType muonGenerator
/generator/setMuonEffectiveDepth 6.0 km

#Output commands
/output/enableNeutronTallyOutput true
/output/setOutputFile outputFiles/test.root

/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/beamOn 1000000
